### ISSUE TITLE
th_ecdh allowed to cache derived secret?

### ISSUE THREAD

**Issue by stevew817** [eembc/securemark-tls#26]
The current definition of the `th_ecdh` DUT API opens up for doing the time-intensive calculation at init time instead of the function that's being called during profiling. Is that intended?

I'd suggest supplying the public key to derive against in the `calc_secret` function instead of during init to enforce actually doing the operation on each iteration.

**Comment by stevew817** [comment]
Nevermind - I was looking at the main branch instead of v2.

**Comment by stevew817** [comment]
Well - actually, the same issue is present in v2.

https://github.com/eembc/securemark-tls/blob/83700423e4692cf798e60820845dae200268ca99/profile/th_api/th_ecdh.c#L37

The public key to derive against is set separately from the function retrieving the secret. Thus, a DUT could potentially do the calculation upon setting the public key instead of during the calc_secret step. Is this intended?

**Comment by petertorelli** [comment]
> Thus, a DUT could potentially do the calculation upon setting the public key instead of during the calc_secret step.

That's a really good catch! There's nothing in the API preventing the calculation from happening in public key load (outside timing loop), since it has its private and the peer public keys. I'll investigate with the team and get back to you.

**Comment by petertorelli** [comment]
The team agreed to move the peer public load into the timing loop. Thanks!
